### ISSUE TITLE
Application error: a client-side exception has occurred (see the browser console for more information).

### ISSUE THREAD

**Issue by Afaqak** [gridaco/code#212]
I keep getting this error

**Comment by softmarshmallow** [comment]
@Afaqak can you share the log from the browser console? (Chrome devtools)

**Comment by jamesaja2** [comment]
Failed to load resource: the server responded with a status of 401 ()Understand this errorAI
framework-8f942920e8119434.js:9 cannot get main ImageRepositories. set it via `MainImageRepository.set()` before calling this.
a5 @ framework-8f942920e8119434.js:9Understand this errorAI
main-550069a4efc5c0fe.js:1 cannot get main ImageRepositories. set it via `MainImageRepository.set()` before calling this.
Z @ main-550069a4efc5c0fe.js:1Understand this errorAI
main-550069a4efc5c0fe.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
Z @ main-550069a4efc5c0fe.js:1Understand this errorAI
framework-8f942920e8119434.js:9 cannot get main ImageRepositories. set it via `MainImageRepository.set()` before calling this.
a5 @ framework-8f942920e8119434.js:9Understand this errorAI
main-550069a4efc5c0fe.js:1 cannot get main ImageRepositories. set it via `MainImageRepository.set()` before calling this.
Z @ main-550069a4efc5c0fe.js:1Understand this errorAI
main-550069a4efc5c0fe.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
Z @ main-550069a4efc5c0fe.js:1Understand this errorAI
framework-8f942920e8119434.js:9 cannot get main ImageRepositories. set it via `MainImageRepository.set()` before calling this.
a5 @ framework-8f942920e8119434.js:9Understand this errorAI
main-550069a4efc5c0fe.js:1 cannot get main ImageRepositories. set it via `MainImageRepository.set()` before calling this.
Z @ main-550069a4efc5c0fe.js:1Understand this errorAI
main-550069a4efc5c0fe.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
Z @ main-550069a4efc5c0fe.js:1Understand this errorAI
2main-550069a4efc5c0fe.js:1 Error rendering page:  Error: Cancel rendering route
    at c (main-550069a4efc5c0fe.js:1:13869)
    at main-550069a4efc5c0fe.js:1:13821
    at new Promise (<anonymous>)
    at es (main-550069a4efc5c0fe.js:1:13798)
    at main-550069a4efc5c0fe.js:1:12042
